//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Profiler.ProfilerService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoapPortBinding", Namespace="http://sanpaoloimi.com/SSO")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractResponseType))]
    public partial class ServiceSoap : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getProfilazioneOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUtentiOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFunzioniOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAnagraficaUtenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback isProfilatoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNbpProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceSoap() {
            this.Url = global::Profiler.Properties.Settings.Default.Profiler_ProfilerService_ServiceSoap;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getProfilazioneCompletedEventHandler getProfilazioneCompleted;
        
        /// <remarks/>
        public event getUtentiCompletedEventHandler getUtentiCompleted;
        
        /// <remarks/>
        public event getFunzioniCompletedEventHandler getFunzioniCompleted;
        
        /// <remarks/>
        public event getAnagraficaUtenteCompletedEventHandler getAnagraficaUtenteCompleted;
        
        /// <remarks/>
        public event isProfilatoCompletedEventHandler isProfilatoCompleted;
        
        /// <remarks/>
        public event getNbpProfileCompletedEventHandler getNbpProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sanpaoloimi.com/SSO", ResponseNamespace="http://sanpaoloimi.com/SSO", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getProfilazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public profilazioneType getProfilazione([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string userId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string azienda, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string abilSSA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string abilAcronimo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string flagAnagraficaUtente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string flagAnagraficaFunzione, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string flagDecodificaProfili, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraAbilitazioni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraProfili, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraAbilitazioniProfilo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraLivelliDiFacolta, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraIncarichi, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraTutto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string siteName) {
            object[] results = this.Invoke("getProfilazione", new object[] {
                        userId,
                        azienda,
                        uo,
                        abilSSA,
                        abilAcronimo,
                        flagAnagraficaUtente,
                        flagAnagraficaFunzione,
                        flagDecodificaProfili,
                        filtraAbilitazioni,
                        filtraProfili,
                        filtraAbilitazioniProfilo,
                        filtraLivelliDiFacolta,
                        filtraIncarichi,
                        filtraTutto,
                        siteName});
            return ((profilazioneType)(results[0]));
        }
        
        /// <remarks/>
        public void getProfilazioneAsync(string userId, string azienda, string uo, string abilSSA, string abilAcronimo, string flagAnagraficaUtente, string flagAnagraficaFunzione, string flagDecodificaProfili, string filtraAbilitazioni, string filtraProfili, string filtraAbilitazioniProfilo, string filtraLivelliDiFacolta, string filtraIncarichi, string filtraTutto, string siteName) {
            this.getProfilazioneAsync(userId, azienda, uo, abilSSA, abilAcronimo, flagAnagraficaUtente, flagAnagraficaFunzione, flagDecodificaProfili, filtraAbilitazioni, filtraProfili, filtraAbilitazioniProfilo, filtraLivelliDiFacolta, filtraIncarichi, filtraTutto, siteName, null);
        }
        
        /// <remarks/>
        public void getProfilazioneAsync(
                    string userId, 
                    string azienda, 
                    string uo, 
                    string abilSSA, 
                    string abilAcronimo, 
                    string flagAnagraficaUtente, 
                    string flagAnagraficaFunzione, 
                    string flagDecodificaProfili, 
                    string filtraAbilitazioni, 
                    string filtraProfili, 
                    string filtraAbilitazioniProfilo, 
                    string filtraLivelliDiFacolta, 
                    string filtraIncarichi, 
                    string filtraTutto, 
                    string siteName, 
                    object userState) {
            if ((this.getProfilazioneOperationCompleted == null)) {
                this.getProfilazioneOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProfilazioneOperationCompleted);
            }
            this.InvokeAsync("getProfilazione", new object[] {
                        userId,
                        azienda,
                        uo,
                        abilSSA,
                        abilAcronimo,
                        flagAnagraficaUtente,
                        flagAnagraficaFunzione,
                        flagDecodificaProfili,
                        filtraAbilitazioni,
                        filtraProfili,
                        filtraAbilitazioniProfilo,
                        filtraLivelliDiFacolta,
                        filtraIncarichi,
                        filtraTutto,
                        siteName}, this.getProfilazioneOperationCompleted, userState);
        }
        
        private void OngetProfilazioneOperationCompleted(object arg) {
            if ((this.getProfilazioneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProfilazioneCompleted(this, new getProfilazioneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sanpaoloimi.com/SSO", ResponseNamespace="http://sanpaoloimi.com/SSO", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getUtenti", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public utentiType getUtenti([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string azienda, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string gerarchia, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string abilSSA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string abilAcronimo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string flagAnagraficaUtente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraAbilitazioni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraProfili, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraAbilitazioniProfilo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraLivelliDiFacolta, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraIncarichi, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraTutto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string siteName) {
            object[] results = this.Invoke("getUtenti", new object[] {
                        azienda,
                        uo,
                        gerarchia,
                        abilSSA,
                        abilAcronimo,
                        flagAnagraficaUtente,
                        filtraAbilitazioni,
                        filtraProfili,
                        filtraAbilitazioniProfilo,
                        filtraLivelliDiFacolta,
                        filtraIncarichi,
                        filtraTutto,
                        siteName});
            return ((utentiType)(results[0]));
        }
        
        /// <remarks/>
        public void getUtentiAsync(string azienda, string uo, string gerarchia, string abilSSA, string abilAcronimo, string flagAnagraficaUtente, string filtraAbilitazioni, string filtraProfili, string filtraAbilitazioniProfilo, string filtraLivelliDiFacolta, string filtraIncarichi, string filtraTutto, string siteName) {
            this.getUtentiAsync(azienda, uo, gerarchia, abilSSA, abilAcronimo, flagAnagraficaUtente, filtraAbilitazioni, filtraProfili, filtraAbilitazioniProfilo, filtraLivelliDiFacolta, filtraIncarichi, filtraTutto, siteName, null);
        }
        
        /// <remarks/>
        public void getUtentiAsync(string azienda, string uo, string gerarchia, string abilSSA, string abilAcronimo, string flagAnagraficaUtente, string filtraAbilitazioni, string filtraProfili, string filtraAbilitazioniProfilo, string filtraLivelliDiFacolta, string filtraIncarichi, string filtraTutto, string siteName, object userState) {
            if ((this.getUtentiOperationCompleted == null)) {
                this.getUtentiOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUtentiOperationCompleted);
            }
            this.InvokeAsync("getUtenti", new object[] {
                        azienda,
                        uo,
                        gerarchia,
                        abilSSA,
                        abilAcronimo,
                        flagAnagraficaUtente,
                        filtraAbilitazioni,
                        filtraProfili,
                        filtraAbilitazioniProfilo,
                        filtraLivelliDiFacolta,
                        filtraIncarichi,
                        filtraTutto,
                        siteName}, this.getUtentiOperationCompleted, userState);
        }
        
        private void OngetUtentiOperationCompleted(object arg) {
            if ((this.getUtentiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUtentiCompleted(this, new getUtentiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sanpaoloimi.com/SSO", ResponseNamespace="http://sanpaoloimi.com/SSO", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getFunzioni", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public funzioniType getFunzioni([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string azienda, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string descrizioneFunzione, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string abilTAG, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string abilSSA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string abilAcronimo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraAbilitazioni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraProfili, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraAbilitazioniProfilo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraLivelliDiFacolta, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraIncarichi, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraTutto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string siteName) {
            object[] results = this.Invoke("getFunzioni", new object[] {
                        azienda,
                        uo,
                        descrizioneFunzione,
                        abilTAG,
                        abilSSA,
                        abilAcronimo,
                        filtraAbilitazioni,
                        filtraProfili,
                        filtraAbilitazioniProfilo,
                        filtraLivelliDiFacolta,
                        filtraIncarichi,
                        filtraTutto,
                        siteName});
            return ((funzioniType)(results[0]));
        }
        
        /// <remarks/>
        public void getFunzioniAsync(string azienda, string uo, string descrizioneFunzione, string abilTAG, string abilSSA, string abilAcronimo, string filtraAbilitazioni, string filtraProfili, string filtraAbilitazioniProfilo, string filtraLivelliDiFacolta, string filtraIncarichi, string filtraTutto, string siteName) {
            this.getFunzioniAsync(azienda, uo, descrizioneFunzione, abilTAG, abilSSA, abilAcronimo, filtraAbilitazioni, filtraProfili, filtraAbilitazioniProfilo, filtraLivelliDiFacolta, filtraIncarichi, filtraTutto, siteName, null);
        }
        
        /// <remarks/>
        public void getFunzioniAsync(string azienda, string uo, string descrizioneFunzione, string abilTAG, string abilSSA, string abilAcronimo, string filtraAbilitazioni, string filtraProfili, string filtraAbilitazioniProfilo, string filtraLivelliDiFacolta, string filtraIncarichi, string filtraTutto, string siteName, object userState) {
            if ((this.getFunzioniOperationCompleted == null)) {
                this.getFunzioniOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFunzioniOperationCompleted);
            }
            this.InvokeAsync("getFunzioni", new object[] {
                        azienda,
                        uo,
                        descrizioneFunzione,
                        abilTAG,
                        abilSSA,
                        abilAcronimo,
                        filtraAbilitazioni,
                        filtraProfili,
                        filtraAbilitazioniProfilo,
                        filtraLivelliDiFacolta,
                        filtraIncarichi,
                        filtraTutto,
                        siteName}, this.getFunzioniOperationCompleted, userState);
        }
        
        private void OngetFunzioniOperationCompleted(object arg) {
            if ((this.getFunzioniCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFunzioniCompleted(this, new getFunzioniCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sanpaoloimi.com/SSO", ResponseNamespace="http://sanpaoloimi.com/SSO", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAnagraficaUtente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anagraficaUtenteMultiplaType getAnagraficaUtente([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string userId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string siteName, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string codiceFiscale) {
            object[] results = this.Invoke("getAnagraficaUtente", new object[] {
                        userId,
                        siteName,
                        codiceFiscale});
            return ((anagraficaUtenteMultiplaType)(results[0]));
        }
        
        /// <remarks/>
        public void getAnagraficaUtenteAsync(string userId, string siteName, string codiceFiscale) {
            this.getAnagraficaUtenteAsync(userId, siteName, codiceFiscale, null);
        }
        
        /// <remarks/>
        public void getAnagraficaUtenteAsync(string userId, string siteName, string codiceFiscale, object userState) {
            if ((this.getAnagraficaUtenteOperationCompleted == null)) {
                this.getAnagraficaUtenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAnagraficaUtenteOperationCompleted);
            }
            this.InvokeAsync("getAnagraficaUtente", new object[] {
                        userId,
                        siteName,
                        codiceFiscale}, this.getAnagraficaUtenteOperationCompleted, userState);
        }
        
        private void OngetAnagraficaUtenteOperationCompleted(object arg) {
            if ((this.getAnagraficaUtenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAnagraficaUtenteCompleted(this, new getAnagraficaUtenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sanpaoloimi.com/SSO", ResponseNamespace="http://sanpaoloimi.com/SSO", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("isProfilato", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public isProfilatoType isProfilato([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string userId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string azienda, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string abilSSA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string abilAcronimo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraAbilitazioni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraProfili, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraAbilitazioniProfilo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraLivelliDiFacolta, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraIncarichi, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string filtraTutto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string siteName) {
            object[] results = this.Invoke("isProfilato", new object[] {
                        userId,
                        azienda,
                        uo,
                        abilSSA,
                        abilAcronimo,
                        filtraAbilitazioni,
                        filtraProfili,
                        filtraAbilitazioniProfilo,
                        filtraLivelliDiFacolta,
                        filtraIncarichi,
                        filtraTutto,
                        siteName});
            return ((isProfilatoType)(results[0]));
        }
        
        /// <remarks/>
        public void isProfilatoAsync(string userId, string azienda, string uo, string abilSSA, string abilAcronimo, string filtraAbilitazioni, string filtraProfili, string filtraAbilitazioniProfilo, string filtraLivelliDiFacolta, string filtraIncarichi, string filtraTutto, string siteName) {
            this.isProfilatoAsync(userId, azienda, uo, abilSSA, abilAcronimo, filtraAbilitazioni, filtraProfili, filtraAbilitazioniProfilo, filtraLivelliDiFacolta, filtraIncarichi, filtraTutto, siteName, null);
        }
        
        /// <remarks/>
        public void isProfilatoAsync(string userId, string azienda, string uo, string abilSSA, string abilAcronimo, string filtraAbilitazioni, string filtraProfili, string filtraAbilitazioniProfilo, string filtraLivelliDiFacolta, string filtraIncarichi, string filtraTutto, string siteName, object userState) {
            if ((this.isProfilatoOperationCompleted == null)) {
                this.isProfilatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisProfilatoOperationCompleted);
            }
            this.InvokeAsync("isProfilato", new object[] {
                        userId,
                        azienda,
                        uo,
                        abilSSA,
                        abilAcronimo,
                        filtraAbilitazioni,
                        filtraProfili,
                        filtraAbilitazioniProfilo,
                        filtraLivelliDiFacolta,
                        filtraIncarichi,
                        filtraTutto,
                        siteName}, this.isProfilatoOperationCompleted, userState);
        }
        
        private void OnisProfilatoOperationCompleted(object arg) {
            if ((this.isProfilatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isProfilatoCompleted(this, new isProfilatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sanpaoloimi.com/SSO", ResponseNamespace="http://sanpaoloimi.com/SSO", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getNbpProfile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nbpProfilazioneType getNbpProfile([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string userId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string abilAcronimo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tipoQuery, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string siteName) {
            object[] results = this.Invoke("getNbpProfile", new object[] {
                        userId,
                        abilAcronimo,
                        tipoQuery,
                        siteName});
            return ((nbpProfilazioneType)(results[0]));
        }
        
        /// <remarks/>
        public void getNbpProfileAsync(string userId, string abilAcronimo, string tipoQuery, string siteName) {
            this.getNbpProfileAsync(userId, abilAcronimo, tipoQuery, siteName, null);
        }
        
        /// <remarks/>
        public void getNbpProfileAsync(string userId, string abilAcronimo, string tipoQuery, string siteName, object userState) {
            if ((this.getNbpProfileOperationCompleted == null)) {
                this.getNbpProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNbpProfileOperationCompleted);
            }
            this.InvokeAsync("getNbpProfile", new object[] {
                        userId,
                        abilAcronimo,
                        tipoQuery,
                        siteName}, this.getNbpProfileOperationCompleted, userState);
        }
        
        private void OngetNbpProfileOperationCompleted(object arg) {
            if ((this.getNbpProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNbpProfileCompleted(this, new getNbpProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class profilazioneType : abstractResponseType {
        
        private profilazioneBodyType profilazioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public profilazioneBodyType profilazione {
            get {
                return this.profilazioneField;
            }
            set {
                this.profilazioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class profilazioneBodyType {
        
        private anagraficaUtenteBodyType anagraficaUtenteField;
        
        private abilitazioniProfiloType[] decodificaProfiliField;
        
        private userInfoTypeUtentu[] userinfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anagraficaUtenteBodyType anagraficaUtente {
            get {
                return this.anagraficaUtenteField;
            }
            set {
                this.anagraficaUtenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("decodificaProfilo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public abilitazioniProfiloType[] decodificaProfili {
            get {
                return this.decodificaProfiliField;
            }
            set {
                this.decodificaProfiliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userinfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userInfoTypeUtentu[] userinfo {
            get {
                return this.userinfoField;
            }
            set {
                this.userinfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class anagraficaUtenteBodyType {
        
        private string userIdField;
        
        private string nomeField;
        
        private string cognomeField;
        
        private string codiceFiscaleField;
        
        private string emailField;
        
        private string telefonoField;
        
        private string cellulareField;
        
        private string figuraProfessionaleField;
        
        private string aziendaField;
        
        private string descAziendaField;
        
        private string uoField;
        
        private string descUoField;
        
        private string societaField;
        
        private string descSocietaField;
        
        private string tipoDipendenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                this.cognomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codiceFiscale {
            get {
                return this.codiceFiscaleField;
            }
            set {
                this.codiceFiscaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cellulare {
            get {
                return this.cellulareField;
            }
            set {
                this.cellulareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string figuraProfessionale {
            get {
                return this.figuraProfessionaleField;
            }
            set {
                this.figuraProfessionaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string azienda {
            get {
                return this.aziendaField;
            }
            set {
                this.aziendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descAzienda {
            get {
                return this.descAziendaField;
            }
            set {
                this.descAziendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uo {
            get {
                return this.uoField;
            }
            set {
                this.uoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descUo {
            get {
                return this.descUoField;
            }
            set {
                this.descUoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string societa {
            get {
                return this.societaField;
            }
            set {
                this.societaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descSocieta {
            get {
                return this.descSocietaField;
            }
            set {
                this.descSocietaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDipendente {
            get {
                return this.tipoDipendenteField;
            }
            set {
                this.tipoDipendenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class anagraficaAbilitazioneType {
        
        private string ssaField;
        
        private string acronimoField;
        
        private string tipo_ambienteField;
        
        private string tipo_operativitaField;
        
        private string tipo_utenzaField;
        
        private string incompatibileField;
        
        private string richiedenteField;
        
        private string tagsField;
        
        private string abil_desc_itaField;
        
        private string abil_desc_engField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ssa {
            get {
                return this.ssaField;
            }
            set {
                this.ssaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acronimo {
            get {
                return this.acronimoField;
            }
            set {
                this.acronimoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo_ambiente {
            get {
                return this.tipo_ambienteField;
            }
            set {
                this.tipo_ambienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo_operativita {
            get {
                return this.tipo_operativitaField;
            }
            set {
                this.tipo_operativitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo_utenza {
            get {
                return this.tipo_utenzaField;
            }
            set {
                this.tipo_utenzaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string incompatibile {
            get {
                return this.incompatibileField;
            }
            set {
                this.incompatibileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string richiedente {
            get {
                return this.richiedenteField;
            }
            set {
                this.richiedenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string abil_desc_ita {
            get {
                return this.abil_desc_itaField;
            }
            set {
                this.abil_desc_itaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string abil_desc_eng {
            get {
                return this.abil_desc_engField;
            }
            set {
                this.abil_desc_engField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class funzioniInfoType {
        
        private anagraficaFunzioneSlimType datiAnagraficiFunzioneField;
        
        private anagraficaAbilitazioneType datiAnagraficiAbilitazioneField;
        
        private string[] abilitazioniAssociateField;
        
        private string[] profiliAssociatiField;
        
        private uoInfoType[] uoAssegnabiliField;
        
        private string nameField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anagraficaFunzioneSlimType datiAnagraficiFunzione {
            get {
                return this.datiAnagraficiFunzioneField;
            }
            set {
                this.datiAnagraficiFunzioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anagraficaAbilitazioneType datiAnagraficiAbilitazione {
            get {
                return this.datiAnagraficiAbilitazioneField;
            }
            set {
                this.datiAnagraficiAbilitazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("abilitazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] abilitazioniAssociate {
            get {
                return this.abilitazioniAssociateField;
            }
            set {
                this.abilitazioniAssociateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("profilo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] profiliAssociati {
            get {
                return this.profiliAssociatiField;
            }
            set {
                this.profiliAssociatiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uoinfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public uoInfoType[] uoAssegnabili {
            get {
                return this.uoAssegnabiliField;
            }
            set {
                this.uoAssegnabiliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class anagraficaFunzioneSlimType {
        
        private string codFunzioneField;
        
        private string tipoFunzioneField;
        
        private string descrizioneFunzioneBreveField;
        
        private string descrizioneFunzioneLungaField;
        
        private string tipoUoField;
        
        private string codCategoriaField;
        
        private string flagInoltroField;
        
        private string flagAssegnField;
        
        private string tipoLdfField;
        
        private string dataInizioValiditaField;
        
        private string dataFineValiditaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codFunzione {
            get {
                return this.codFunzioneField;
            }
            set {
                this.codFunzioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoFunzione {
            get {
                return this.tipoFunzioneField;
            }
            set {
                this.tipoFunzioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descrizioneFunzioneBreve {
            get {
                return this.descrizioneFunzioneBreveField;
            }
            set {
                this.descrizioneFunzioneBreveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descrizioneFunzioneLunga {
            get {
                return this.descrizioneFunzioneLungaField;
            }
            set {
                this.descrizioneFunzioneLungaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoUo {
            get {
                return this.tipoUoField;
            }
            set {
                this.tipoUoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codCategoria {
            get {
                return this.codCategoriaField;
            }
            set {
                this.codCategoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flagInoltro {
            get {
                return this.flagInoltroField;
            }
            set {
                this.flagInoltroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flagAssegn {
            get {
                return this.flagAssegnField;
            }
            set {
                this.flagAssegnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoLdf {
            get {
                return this.tipoLdfField;
            }
            set {
                this.tipoLdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataInizioValidita {
            get {
                return this.dataInizioValiditaField;
            }
            set {
                this.dataInizioValiditaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataFineValidita {
            get {
                return this.dataFineValiditaField;
            }
            set {
                this.dataFineValiditaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class uoInfoType {
        
        private userInfoTypeUtenti[] userinfoField;
        
        private string aziendaField;
        
        private string uoField;
        
        private string societaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userinfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userInfoTypeUtenti[] userinfo {
            get {
                return this.userinfoField;
            }
            set {
                this.userinfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string azienda {
            get {
                return this.aziendaField;
            }
            set {
                this.aziendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uo {
            get {
                return this.uoField;
            }
            set {
                this.uoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string societa {
            get {
                return this.societaField;
            }
            set {
                this.societaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class userInfoTypeUtenti {
        
        private anagraficaUtenteBodyType anagraficaUtenteField;
        
        private string utenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anagraficaUtenteBodyType anagraficaUtente {
            get {
                return this.anagraficaUtenteField;
            }
            set {
                this.anagraficaUtenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utente {
            get {
                return this.utenteField;
            }
            set {
                this.utenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class servizioType {
        
        private string serviceidField;
        
        private string endpointField;
        
        private string abilitazioneField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serviceid {
            get {
                return this.serviceidField;
            }
            set {
                this.serviceidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string abilitazione {
            get {
                return this.abilitazioneField;
            }
            set {
                this.abilitazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class abilitazioniProfiloType {
        
        private funzioneType[] abilitazioneField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("abilitazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public funzioneType[] abilitazione {
            get {
                return this.abilitazioneField;
            }
            set {
                this.abilitazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class funzioneType {
        
        private anagraficaFunzioneSlimType anagraficaFunzioneField;
        
        private string codiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anagraficaFunzioneSlimType anagraficaFunzione {
            get {
                return this.anagraficaFunzioneField;
            }
            set {
                this.anagraficaFunzioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class userProfileType {
        
        private funzioneType[] abilitazioniField;
        
        private funzioneType[] profiliField;
        
        private abilitazioniProfiloType[] abilitazioniProfiloField;
        
        private funzioneType[] livelliDiFacoltaField;
        
        private funzioneType[] incarichiField;
        
        private string aziendaField;
        
        private string uoField;
        
        private string societaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("abilitazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public funzioneType[] abilitazioni {
            get {
                return this.abilitazioniField;
            }
            set {
                this.abilitazioniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("profilo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public funzioneType[] profili {
            get {
                return this.profiliField;
            }
            set {
                this.profiliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("abilitazioniProfilo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public abilitazioniProfiloType[] abilitazioniProfilo {
            get {
                return this.abilitazioniProfiloField;
            }
            set {
                this.abilitazioniProfiloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("livelloDiFacolta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public funzioneType[] livelliDiFacolta {
            get {
                return this.livelliDiFacoltaField;
            }
            set {
                this.livelliDiFacoltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("incarico", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public funzioneType[] incarichi {
            get {
                return this.incarichiField;
            }
            set {
                this.incarichiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string azienda {
            get {
                return this.aziendaField;
            }
            set {
                this.aziendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uo {
            get {
                return this.uoField;
            }
            set {
                this.uoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string societa {
            get {
                return this.societaField;
            }
            set {
                this.societaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class userInfoTypeUtentu {
        
        private userProfileType[] userprofileField;
        
        private string utenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userprofile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userProfileType[] userprofile {
            get {
                return this.userprofileField;
            }
            set {
                this.userprofileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utente {
            get {
                return this.utenteField;
            }
            set {
                this.utenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class nbpProfilazioneBodyType {
        
        private userInfoTypeUtentu userinfoField;
        
        private servizioType[] serviziField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userInfoTypeUtentu userinfo {
            get {
                return this.userinfoField;
            }
            set {
                this.userinfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("servizio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public servizioType[] servizi {
            get {
                return this.serviziField;
            }
            set {
                this.serviziField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class responseHeaderType {
        
        private string retCodeField;
        
        private string retDescField;
        
        private string messageField;
        
        private int numeroElementiField;
        
        private bool numeroElementiFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string retDesc {
            get {
                return this.retDescField;
            }
            set {
                this.retDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroElementi {
            get {
                return this.numeroElementiField;
            }
            set {
                this.numeroElementiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroElementiSpecified {
            get {
                return this.numeroElementiFieldSpecified;
            }
            set {
                this.numeroElementiFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(isProfilatoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(profilazioneType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(funzioniType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(nbpProfilazioneType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(utentiType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(anagraficaUtenteMultiplaType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public abstract partial class abstractResponseType {
        
        private responseHeaderType responseStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseHeaderType responseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class isProfilatoType : abstractResponseType {
        
        private bool isProfilatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isProfilato {
            get {
                return this.isProfilatoField;
            }
            set {
                this.isProfilatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class funzioniType : abstractResponseType {
        
        private funzioniInfoType[] funzioniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("funzioneInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public funzioniInfoType[] funzioni {
            get {
                return this.funzioniField;
            }
            set {
                this.funzioniField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class nbpProfilazioneType : abstractResponseType {
        
        private nbpProfilazioneBodyType profilazioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nbpProfilazioneBodyType profilazione {
            get {
                return this.profilazioneField;
            }
            set {
                this.profilazioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class utentiType : abstractResponseType {
        
        private uoInfoType[] utentiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UOinfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public uoInfoType[] utenti {
            get {
                return this.utentiField;
            }
            set {
                this.utentiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sanpaoloimi.com/SSO")]
    public partial class anagraficaUtenteMultiplaType : abstractResponseType {
        
        private anagraficaUtenteBodyType[] datiAnagraficiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datiAnagrafici", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anagraficaUtenteBodyType[] datiAnagrafici {
            get {
                return this.datiAnagraficiField;
            }
            set {
                this.datiAnagraficiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getProfilazioneCompletedEventHandler(object sender, getProfilazioneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProfilazioneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProfilazioneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public profilazioneType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((profilazioneType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getUtentiCompletedEventHandler(object sender, getUtentiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUtentiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUtentiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public utentiType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((utentiType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getFunzioniCompletedEventHandler(object sender, getFunzioniCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFunzioniCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFunzioniCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public funzioniType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((funzioniType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getAnagraficaUtenteCompletedEventHandler(object sender, getAnagraficaUtenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAnagraficaUtenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAnagraficaUtenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public anagraficaUtenteMultiplaType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((anagraficaUtenteMultiplaType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void isProfilatoCompletedEventHandler(object sender, isProfilatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isProfilatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isProfilatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public isProfilatoType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((isProfilatoType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getNbpProfileCompletedEventHandler(object sender, getNbpProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNbpProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNbpProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public nbpProfilazioneType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((nbpProfilazioneType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591